WIDTH = 70
HEIGHT = 30
# --- TIEMPO ---
TICK_TIME = 0.2

# --- VIDA ---
MIN_ENERGY = 20
MAX_ENERGY = 35
MIN_AGE = 0
MIN_REPRO_AGE = 16
MIN_REPRO_ENERGY = 14
MAX_AGE_MIN = 80
MAX_AGE_MAX = 130

# Energy
REST_ENERGY_DECAY = 0.15
MOVE_ENERGY_DECAY = 0.4

# --- REPRODUCCIÓN ---
REPRO_CHANCE = 0.05  # bajar
REPRO_COST = 6  # subir

# --- POBLACIÓN ---
INITIAL_POP = 6
SOFT_POP_CAP = 30  # después baja la reproducción
ENERGY_DECAY = 0.4  # en vez de 1 por tick

# --- SÍMBOLOS ---
SYMBOL_YOUNG = "o"
SYMBOL_ADULT = "O"
SYMBOL_OLD = "0"
SYMBOL_SETTLED = "▲"

# UI
MAX_LOGS = 20

# Settlements
BORDER_DISTANCE = 5
SETTLER_TIMER = 5
SETTLEMENT_MIN_MEMBERS = 3

# Tiles
MAX_TILE_POPULATION = 2

CONFLICT_THRESHOLD = 1.1

# WAR
BASE_HIT = 0.04

# Render
TILE_SIZE = 13
SCREEN_W = 1280
SCREEN_H = 720
UI_HEIGHT = 180

# World
RIVERS = 2

#ENTITY
DAILY_FOOD_CONSUMPTION = 1
MAX_DAY_WITHOUT_FOOD = 1


SETTLEMENT_MAX_EMPTY_DAYS = 4